encrypt:
  key-store:
    location: classpath:/server.jks
    password: password
    alias: mytestkey
    secret: changeme
    
    
server:
   port: 8998
   
spring:
   cloud:
     config:
      server:
       git:
        uri: C:/Users/AI5044554/Desktop/config